week1-task1
AlexGenK/kottans-kharkiv-2016 pull request #1
Opened 2016-11-04 10:11 UTC by AlexGenK

2016-11-06 18:09 UTC, SmyzerT requested changes

2016-11-06 18:09 UTC, SmyzerT commented on week1-task1/app.rb
> +configure :development do
конфигурацию лучше вынести в отдельный файл

2016-11-06 18:09 UTC, SmyzerT commented on week1-task1/app.rb
> +class Message < ActiveRecord::Base
определения классов тоже лучше в отдельных файлах делать

2016-11-06 18:09 UTC, SmyzerT commented on week1-task1/app.rb
> +    if ((self.method=="visits") && (self.count==0))||((self.method=="hours") && (Time.now.utc > self.created_at+3600*self.count))
лучше проверки разделить на два метода `visti_limit_reched?` and `time_expired?`

и self можно поудалять

2016-11-06 18:09 UTC, SmyzerT commented on week1-task1/app.rb
> +  def destroyer?
всю логику с удалением лучше вынести в отдельный класс, так как сама модель просто хранит может делать CRUD операции со данными

2016-11-06 18:09 UTC, SmyzerT commented on week1-task1/app.rb
> +  def decrement_count!
👍

2016-11-06 18:09 UTC, SmyzerT commented on week1-task1/app.rb
> +  def initialize size, links_list
передавать список ссылок довольно рисково, как тольк у тебя будет много сообщений твое приложение начнет сильно тормозить, нужно просто спрашивать у модели уникальная ли ссылка которую мы хотим созадать и все? а сама модель через sql уже будет смотреть уникальна ссылка или нет

2016-11-06 18:09 UTC, SmyzerT commented on week1-task1/app.rb
> +  @m=Message.new(params[:message])
всю логику по созданию сообщения можно перенести в новый класс `PostMessage`передавть туда параметры и все, и возвращать результат операции

2016-11-06 18:09 UTC, SmyzerT commented on week1-task1/app.rb
> +end
нужно оставлять последнюю пустую строку

2016-11-06 18:09 UTC, SmyzerT commented on week1-task1/public/js/app.js
> +function encrypt_message(message, password, target, error_field) {
SOLID касается любого кода, даже js) 😃

2016-11-06 18:10 UTC, SmyzerT commented
проделана хорошая работа)

2016-11-10 09:12 UTC, AlexGenK commented
Блин! Сам не понял, как закрыл :(

2016-11-10 09:26 UTC, SmyzerT commented
та ничего страшного)

2016-11-24 05:19 UTC, merged