create Ebuberable class
AlexGenK/kottans-kharkiv-2016 pull request #2
Opened 2016-11-06 10:41 UTC by AlexGenK

Первый пункт из домашки. Вроде все работает как надо.
Пока реализовывал reduce, чуть не сломал себе мозг :)

2016-11-07 12:19 UTC, zverok requested changes
Код хороший (не считая замечаний), спеки так себе, но до этого дело ещё дойдёт :)

2016-11-07 12:19 UTC, zverok commented on week1-task2/Ebuberator/app.rb
> +    block||=proc{|item| item}
`block ||= :itself.to_proc` ;)

2016-11-07 12:19 UTC, zverok commented on week1-task2/Ebuberator/app.rb
> +    end
Слишком много `if`-ов получилось.
Что мы можем тут сделать:
1. всё вычисление должно быть, в идеале, единожды, у нас же тут повторение `each`. Мы можем добиться этого сделав блок из символа методом `to_proc`;
2. тут перемешались два условия «есть ли у нас начальное значение» и «используем ли мы блок или символ»; их можно разделить и сделать независимыми.

Можно попробовать не разделять аргументы `def reduce(*args, &block)`, и использовать `pop` чтобы получить «последний из аргументов», и проверить что у нас там.

2016-11-07 12:19 UTC, zverok commented on week1-task2/Ebuberator/app.rb
> +  def map(&block)
А если блок не передать, что будет?

2016-11-10 10:00 UTC, zverok requested changes

2016-11-10 10:00 UTC, zverok commented on week1-task2/Ebuberator/app.rb
> +    block=args.last.to_proc if Symbol===args.last
Лучше `is_a?`, точнее смысл выражает.

2016-11-10 10:00 UTC, zverok commented on week1-task2/Ebuberator/app.rb
> +    block_given? ? each {|item| out << block.call(item)} : each {|item| out << item}
Неправда.

```ruby
[1,2,3].map
# => #<Enumerator: [1, 2, 3]:map>
```

2016-11-11 13:18 UTC, AlexGenK commented on week1-task2/Ebuberator/app.rb
> +    block=args.last.to_proc if Symbol===args.last
Хм. Про такую форму сравнения я не знал. Действительно более осмысленно.

2016-11-13 12:05 UTC, zverok approved these changes

2016-11-13 12:05 UTC, zverok commented on week1-task2/Ebuberator/app.rb
> +    accum=args.first unless args.first.is_a? Symbol
если в стр.35 сделать `block = args.last.to_proc if ...`, то в стр.36 дополнительный unless не понадобится. И, кстати, строка 34 тоже ;)

А так всё отлично.

2016-11-14 08:43 UTC, AlexGenK commented on week1-task2/Ebuberator/app.rb
> +    accum=args.first unless args.first.is_a? Symbol
Но как!!!

2016-11-15 13:26 UTC, zverok commented on week1-task2/Ebuberator/app.rb
> +    accum=args.first unless args.first.is_a? Symbol
Так а чо как-то?

``` ruby
block=args.pop.to_proc if args.last.is_a? Symbol
accum=args.shift
```

вместо строк 34-36, да и всё.

2016-11-15 13:52 UTC, AlexGenK commented on week1-task2/Ebuberator/app.rb
> +    accum=args.first unless args.first.is_a? Symbol
Аааа, понял! pop и shift меняют же исходный массив. Но почему они без бэнга?

2016-12-11 17:23 UTC, merged